增加 Twikoo 评论系统支持
ppoffice/hexo-component-inferno pull request #40
Opened 2022-04-16 02:43 UTC by Nofated095

如题，增加Twikoo支持

基于<https://www.anzifan.com/post/icarus_to_candy_2/>中的文章

基于腾讯云函数，在主题中需要的更改也提交了PR

2022-04-16 02:43 UTC, Nofated095 commented
https://github.com/ppoffice/hexo-theme-icarus/pull/1065

2022-04-16 02:49 UTC, Nofated095 commented
目前 Twikoo 已经支持更加轻便的 Vercel 部署和 MondoDB。vercel domains即为环境id

<https://twikoo.js.org/quick-start.html#云函数部署>

2022-04-18 15:33 UTC, ppoffice commented
@Nofated095 

1. 请把schema中的`envId`和`comment.envId`改为`env_id`以保持和其他配置项命名规则一致；
1. 可以注释一下组件么？像下面这样：
   https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/comment/waline.jsx

2022-04-19 09:04 UTC, Nofated095 commented
不确定这样子改是否合理

@MannyCooper

2022-04-19 15:06 UTC, ppoffice requested changes

2022-04-19 15:06 UTC, ppoffice commented on src/view/comment/twikoo.jsx
> + *     env_id="Vercel Domain"
这里可以是`envId`，因为此React组件的属性不是`comment`

2022-04-19 15:06 UTC, ppoffice commented on src/view/comment/twikoo.jsx
> + *         jsURL: "https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/twikoo/1.4.18/twikoo.all.min.js"
`jsURL`不是`comment`的属性之一，也没有出现在schema中，所以这里不应该有`jsURL`

2022-04-19 23:07 UTC, merged

2022-04-19 23:11 UTC, ppoffice commented
@Nofated095 你的代码格式不正确，请用`npm run format`修复你的代码并另开一个PR

https://github.com/ppoffice/hexo-component-inferno/runs/6086590190?check_suite_focus=true#step:6:13